<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastReport.OpenSource" Version="2025.1.0" />
    <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2025.1.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="ini-parser-netstandard" Version="2.5.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Wkhtmltopdf.NetCore" Version="3.0.2" />
  </ItemGroup>

</Project>
